"""empty message

Revision ID: 467aea99b7dc
Revises: f94ceb607cc2
Create Date: 2022-05-11 00:33:15.105012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467aea99b7dc'
down_revision = 'f94ceb607cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    # ### end Alembic commands ###
